///////////////////////////////////////////////////////////
//  IBM.cs
//  Implementation of the Class IBM
//  Generated by Enterprise Architect
//  Created on:      05-jun.-2023 19:32:00
//  Original author: gasto
///////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Observador {
	/// <summary>
	/// This class stores the state of interest to ConcreteObserver objects and sends
	/// notification to its observers when its state changes.
	/// </summary>
	public class IBM : Stock {

		public IBM(string symbol, double price)
			: base(symbol, price)
		{
		}

	}//end IBM

}//end namespace Observador